// Frontend/Mobile/src/screens/Welcome.tsx
import { useNavigation } from '@react-navigation/native';
import { StackNavigationProp } from '@react-navigation/stack';
import React from 'react';
import { StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { stackParamList } from '../Navigation/StackNavigation';
import Login from './Auth/Login';
import { SafeAreaView } from 'react-native-safe-area-context';
import LinearGradient from 'react-native-linear-gradient';
import NoteContainer from '../components/NoteContainer';
import SolidButton from '../components/SolidButton';
import OutlineButton from '../components/OutlineButton';
type WelcomeScreenNavigationProp = StackNavigationProp<
  stackParamList,
  'welcome'
>;
const Welcome = (): React.ReactElement => {
  const nav: any = useNavigation();
  function signinHandler() {
    nav.navigate('signin');
  }
  function loginHandler() {
    nav.navigate('login');
  }

  return (
    <LinearGradient
      colors={['#09090b', '#18181b', '#000000']}
      style={styles.gradient}
    >
      <SafeAreaView style={styles.main_container}>
        <Text style={styles.heading_text}>NoteHub</Text>
        <Text style={[styles.descirption_text]}>
          A secure note-taking system to create, edit, and manage your notes.
          Stay organized with fast access across all your devices.
        </Text>
        <NoteContainer
          title="📝 Create & Edit"
          message="Add, update, and delete notes easily with a distraction-free editor."
        />
        <NoteContainer
          title=" 🔐 Secure Access"
          message="Sign up and log in securely to keep your notes private and protected."
        />
        <NoteContainer
          title="⚡ Fast & Reliable"
          message="Optimized for speed so your notes are always just one click away."
        />
        <View style={styles.button_main_container}>
          <View style={styles.button_container}>
            <SolidButton title="Login" opFunc={loginHandler} />
          </View>
          <View style={styles.button_container}>
            <SolidButton title="New here!" opFunc={signinHandler} />
          </View>
        </View>
      </SafeAreaView>
    </LinearGradient>
  );
};
const styles = StyleSheet.create({
  gradient: {
    flex: 1,
  },
  heading_text: {
    fontSize: 50,
    fontWeight: 600,
    textAlign: 'center',
    color: '#66aa6e',
  },
  descirption_text: {
    color: '#AAA8B0',
    textAlign: 'center',
    fontWeight: 500,
    marginVertical: 10,
  },
  main_container: { flex: 1, justifyContent: 'center', marginHorizontal: 10 },
  //
  button_main_container: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginVertical: 10,
  },
  button_container: {
    marginHorizontal: 5,
    width: '49%',
  },
});
export default Welcome;

// Frontend-web/src/app/pages/welcome/welcome.component.ts
import { Component } from '@angular/core';
import { TypewritterComponent } from '../../components/typewritter/typewritter.component';
import { SolidButtonComponent } from '../../components/solid-button/solid-button.component';
import { OutlineButtonComponent } from '../../components/outline-button/outline-button.component';
import { Router } from '@angular/router';
import { OnInit } from '@angular/core';
import { SetSeoService } from '../../services/seo/set-seo.service';
import { appHeading } from '../../constants/appDetails';
import { ButtonHandlersService } from '../../services/ButtonHandlers/button-handlers.service';
@Component({
  selector: 'app-welcome',
  imports: [TypewritterComponent, SolidButtonComponent, OutlineButtonComponent],
  templateUrl: './welcome.component.html',
  styleUrl: './welcome.component.css',
})
export class WelcomeComponent implements OnInit {
  constructor(
    private router: Router,
    private seo: SetSeoService,
    private buttonEvent: ButtonHandlersService
  ) {}
  appHeading: string = appHeading;
  ngOnInit(): void {
    this.seo.setSeo({
      title: 'NoteHub – Simple & Smart Note Taking App',
      description:
        'NoteHub is a simple and smart note taking app to write, save, and organize notes easily. Stay productive with a clean and fast notes app.',
      keyword:
        'note taking app, simple notes app, write notes online, smart note app, productivity notes, notehub',
    });
  }
  loginButtonHandler = () => {
    this.buttonEvent.goToLoginPage();
  };
  singinButtonHandle = () => {
    this.buttonEvent.goToSiginPage();
  };
}

<div class="h-screen">
  <main
    class="min-h-screen w-full flex flex-col items-center justify-center bg-linear-to-br from-zinc-950 via-zinc-900 to-black px-6 text-zinc-100"
  >
    <div class="mb-4">
      <app-typewritter
        [message]="appHeading"
        class="text-4xl md:text-6xl font-semibold tracking-tight text-center"
      />
    </div>
    <p class="max-w-2xl text-center text-zinc-400 text-lg mb-10">
      A secure note-taking system to create, edit, and manage your notes. Stay
      organized with fast access across all your devices.
    </p>
    <div class="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-5xl mb-12">
      <div
        class="bg-zinc-900 border border-zinc-800 rounded-lg p-6 text-center hover:border-zinc-700 transition"
      >
        <h3 class="text-lg font-medium mb-2">📝 Create & Edit</h3>
        <p class="text-zinc-400 text-sm">
          Add, update, and delete notes easily with a distraction-free editor.
        </p>
      </div>

      <div
        class="bg-zinc-900 border border-zinc-800 rounded-lg p-6 text-center hover:border-zinc-700 transition"
      >
        <h3 class="text-lg font-medium mb-2">🔐 Secure Access</h3>
        <p class="text-zinc-400 text-sm">
          Sign up and log in securely to keep your notes private and protected.
        </p>
      </div>

      <div
        class="bg-zinc-900 border border-zinc-800 rounded-lg p-6 text-center hover:border-zinc-700 transition"
      >
        <h3 class="text-lg font-medium mb-2">⚡ Fast & Reliable</h3>
        <p class="text-zinc-400 text-sm">
          Optimized for speed so your notes are always just one click away.
        </p>
      </div>
    </div>
    <div class="flex gap-4">
      <app-solid-button
        button-one
        buttonHeading="Login"
        (clicked)="loginButtonHandler()"
      />
      <app-outline-button
        button-two
        buttonHeading="Creaet a new Account"
        (clicked)="singinButtonHandle()"
      />
    </div>
  </main>
</div>
